### PR TITLE
Removed 'c_str()' from << operator call.

### PR DESCRIPTION
**Pull request by Leo-Nogismus**
See issue #289 for more details.

### CODE REVIEW

**Comment by jefft0** [comment]
Thanks, @Leo-Nogismus . Do you think we should also remove `c_str()` in the two similar lines [right above](https://github.com/IIIM-IS/AERA/blob/17a77127fc81703f9b639c52d9aed303a5f4ff9f/r_exec/init.cpp#L182-L183)?

**Comment by Leo-Nogismus** [comment]
They go into 'std::cout' and seem to work. It only happens when writing to a file. But we can do that, of course, might make sense.

**Comment by Leo-Nogismus** [comment]
Added those lines as well and squashed the commits

**Comment by jefft0** [comment]
Looks great. I already tested on my end. Merging.

**Pull request merged**
